services:
  othegoapp:
    image: othegoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-backend
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped