services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: flutterApp
    volumes:
      - .:/app
      - ./build_output:/app/build/app/outputs/flutter-apk
    working_dir: /app
    command: tail -f /dev/null   # keep container alive
    networks:
      - internal

  db:
    image: mysql:8.0.44-debian
    container_name: othego_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "othego_app"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_data: